name: "Wols-CA MQTT AutomationUploader"
version: "1.0.6"
slug: "wols_ca_uploader"
description: "Uploads automations to HA via MQTT"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  log_level: info
